//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipItSharp.Core.Language.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ShipItSharp.Core.Language.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AreYouSureUpdateVariables {
            get {
                return ResourceManager.GetString("AreYouSureUpdateVariables", resourceCulture);
            }
        }
        
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        internal static string CheckingOptions {
            get {
                return ResourceManager.GetString("CheckingOptions", resourceCulture);
            }
        }
        
        internal static string ConfirmationCheck {
            get {
                return ResourceManager.GetString("ConfirmationCheck", resourceCulture);
            }
        }
        
        internal static string CouldntAddEnvToTeam {
            get {
                return ResourceManager.GetString("CouldntAddEnvToTeam", resourceCulture);
            }
        }
        
        internal static string CurrentPackage {
            get {
                return ResourceManager.GetString("CurrentPackage", resourceCulture);
            }
        }
        
        internal static string CurrentRelease {
            get {
                return ResourceManager.GetString("CurrentRelease", resourceCulture);
            }
        }
        
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        internal static string DeployingTo {
            get {
                return ResourceManager.GetString("DeployingTo", resourceCulture);
            }
        }
        
        internal static string DeployingToMachine {
            get {
                return ResourceManager.GetString("DeployingToMachine", resourceCulture);
            }
        }
        
        internal static string DeployingUsingConfig {
            get {
                return ResourceManager.GetString("DeployingUsingConfig", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string EnvionmentId {
            get {
                return ResourceManager.GetString("EnvionmentId", resourceCulture);
            }
        }
        
        internal static string EnvironmentFound {
            get {
                return ResourceManager.GetString("EnvironmentFound", resourceCulture);
            }
        }
        
        internal static string EnvironmentNotFound {
            get {
                return ResourceManager.GetString("EnvironmentNotFound", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ErrorColumnHeadingMismatch {
            get {
                return ResourceManager.GetString("ErrorColumnHeadingMismatch", resourceCulture);
            }
        }
        
        internal static string ExistingPackage {
            get {
                return ResourceManager.GetString("ExistingPackage", resourceCulture);
            }
        }
        
        internal static string ExistingRelease {
            get {
                return ResourceManager.GetString("ExistingRelease", resourceCulture);
            }
        }
        
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        internal static string FailedParsingVariableFile {
            get {
                return ResourceManager.GetString("FailedParsingVariableFile", resourceCulture);
            }
        }
        
        internal static string FailedUpdatingVariableSet {
            get {
                return ResourceManager.GetString("FailedUpdatingVariableSet", resourceCulture);
            }
        }
        
        internal static string FetchingProjectList {
            get {
                return ResourceManager.GetString("FetchingProjectList", resourceCulture);
            }
        }
        
        internal static string ForceRedeploy {
            get {
                return ResourceManager.GetString("ForceRedeploy", resourceCulture);
            }
        }
        
        internal static string GettingGroupInfo {
            get {
                return ResourceManager.GetString("GettingGroupInfo", resourceCulture);
            }
        }
        
        internal static string GoingToRename {
            get {
                return ResourceManager.GetString("GoingToRename", resourceCulture);
            }
        }
        
        internal static string GoingToSaveProfile {
            get {
                return ResourceManager.GetString("GoingToSaveProfile", resourceCulture);
            }
        }
        
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        internal static string InteractiveRunnerInstructions {
            get {
                return ResourceManager.GetString("InteractiveRunnerInstructions", resourceCulture);
            }
        }
        
        internal static string InteractiveRunnerSelectionInstructions {
            get {
                return ResourceManager.GetString("InteractiveRunnerSelectionInstructions", resourceCulture);
            }
        }
        
        internal static string InvalidReleaseVersion {
            get {
                return ResourceManager.GetString("InvalidReleaseVersion", resourceCulture);
            }
        }
        
        internal static string LifecycleDoesntExist {
            get {
                return ResourceManager.GetString("LifecycleDoesntExist", resourceCulture);
            }
        }
        
        internal static string LifecyclePhaseIsInvalid {
            get {
                return ResourceManager.GetString("LifecyclePhaseIsInvalid", resourceCulture);
            }
        }
        
        internal static string LoadingInfoFor {
            get {
                return ResourceManager.GetString("LoadingInfoFor", resourceCulture);
            }
        }
        
        internal static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NewPackage {
            get {
                return ResourceManager.GetString("NewPackage", resourceCulture);
            }
        }
        
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        internal static string NoMatchingChannel {
            get {
                return ResourceManager.GetString("NoMatchingChannel", resourceCulture);
            }
        }
        
        internal static string NoMatchingEnvironments {
            get {
                return ResourceManager.GetString("NoMatchingEnvironments", resourceCulture);
            }
        }
        
        internal static string NoMatchingMachine {
            get {
                return ResourceManager.GetString("NoMatchingMachine", resourceCulture);
            }
        }
        
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        internal static string OnSource {
            get {
                return ResourceManager.GetString("OnSource", resourceCulture);
            }
        }
        
        internal static string OnTarget {
            get {
                return ResourceManager.GetString("OnTarget", resourceCulture);
            }
        }
        
        internal static string PackageNotSelectable {
            get {
                return ResourceManager.GetString("PackageNotSelectable", resourceCulture);
            }
        }
        
        internal static string NoSuitablePackageFound {
            get {
                return ResourceManager.GetString("NoSuitablePackageFound", resourceCulture);
            }
        }
        
        internal static string ParameterNotANumber {
            get {
                return ResourceManager.GetString("ParameterNotANumber", resourceCulture);
            }
        }
        
        internal static string PathDoesntExist {
            get {
                return ResourceManager.GetString("PathDoesntExist", resourceCulture);
            }
        }
        
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        internal static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        internal static string PromotingTo {
            get {
                return ResourceManager.GetString("PromotingTo", resourceCulture);
            }
        }
        
        internal static string PromotingToMachine {
            get {
                return ResourceManager.GetString("PromotingToMachine", resourceCulture);
            }
        }
        
        internal static string ReleaseNamePrompt {
            get {
                return ResourceManager.GetString("ReleaseNamePrompt", resourceCulture);
            }
        }
        
        internal static string RestrictToGroupsPrompt {
            get {
                return ResourceManager.GetString("RestrictToGroupsPrompt", resourceCulture);
            }
        }
        
        internal static string SleepingForSeconds {
            get {
                return ResourceManager.GetString("SleepingForSeconds", resourceCulture);
            }
        }
        
        internal static string SourceEnvironment {
            get {
                return ResourceManager.GetString("SourceEnvironment", resourceCulture);
            }
        }
        
        internal static string TeamDoesntExist {
            get {
                return ResourceManager.GetString("TeamDoesntExist", resourceCulture);
            }
        }
        
        internal static string TooManyMatchingEnvironments {
            get {
                return ResourceManager.GetString("TooManyMatchingEnvironments", resourceCulture);
            }
        }
        
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        internal static string UpdateAvailableHere {
            get {
                return ResourceManager.GetString("UpdateAvailableHere", resourceCulture);
            }
        }
        
        internal static string UpdatingVariableSet {
            get {
                return ResourceManager.GetString("UpdatingVariableSet", resourceCulture);
            }
        }
        
        internal static string UsingProfileAtPath {
            get {
                return ResourceManager.GetString("UsingProfileAtPath", resourceCulture);
            }
        }
        
        internal static string UsingProfileDirAtPath {
            get {
                return ResourceManager.GetString("UsingProfileDirAtPath", resourceCulture);
            }
        }
        
        internal static string VariablePrompt {
            get {
                return ResourceManager.GetString("VariablePrompt", resourceCulture);
            }
        }
        
        internal static string VariablePromptAllowedValues {
            get {
                return ResourceManager.GetString("VariablePromptAllowedValues", resourceCulture);
            }
        }
        
        internal static string WhichChannelPrompt {
            get {
                return ResourceManager.GetString("WhichChannelPrompt", resourceCulture);
            }
        }
        
        internal static string WhichEnvironmentPrompt {
            get {
                return ResourceManager.GetString("WhichEnvironmentPrompt", resourceCulture);
            }
        }
        
        internal static string DownloadAvailableHere {
            get {
                return ResourceManager.GetString("DownloadAvailableHere", resourceCulture);
            }
        }
        
        internal static string BuildingDeploymentJob {
            get {
                return ResourceManager.GetString("BuildingDeploymentJob", resourceCulture);
            }
        }
        
        internal static string CouldntRemoveChannelReleases {
            get {
                return ResourceManager.GetString("CouldntRemoveChannelReleases", resourceCulture);
            }
        }
        
        internal static string RemovingChannel {
            get {
                return ResourceManager.GetString("RemovingChannel", resourceCulture);
            }
        }
        
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        internal static string OldestPackagePublish {
            get {
                return ResourceManager.GetString("OldestPackagePublish", resourceCulture);
            }
        }
        
        internal static string PackageAgeDays {
            get {
                return ResourceManager.GetString("PackageAgeDays", resourceCulture);
            }
        }
        
        internal static string PackageLastModified {
            get {
                return ResourceManager.GetString("PackageLastModified", resourceCulture);
            }
        }
        
        internal static string DeployingSpecificRelease {
            get {
                return ResourceManager.GetString("DeployingSpecificRelease", resourceCulture);
            }
        }
        
        internal static string DeployingSpecificReleaseToMachine {
            get {
                return ResourceManager.GetString("DeployingSpecificReleaseToMachine", resourceCulture);
            }
        }
        
        internal static string ReleaseName {
            get {
                return ResourceManager.GetString("ReleaseName", resourceCulture);
            }
        }
        
        internal static string ReleaseToDeploy {
            get {
                return ResourceManager.GetString("ReleaseToDeploy", resourceCulture);
            }
        }
        
        internal static string FallbackToChannel {
            get {
                return ResourceManager.GetString("FallbackToChannel", resourceCulture);
            }
        }
        
        internal static string ReleaseNotSelectable {
            get {
                return ResourceManager.GetString("ReleaseNotSelectable", resourceCulture);
            }
        }
        
        internal static string DeployRunner_GenerateProjectDeployment_No_packages_found_for__0_ {
            get {
                return ResourceManager.GetString("DeployRunner_GenerateProjectDeployment_No_packages_found_for__0_", resourceCulture);
            }
        }
        
        internal static string NoPackagesFound {
            get {
                return ResourceManager.GetString("NoPackagesFound", resourceCulture);
            }
        }
        
        internal static string TotalRows {
            get {
                return ResourceManager.GetString("TotalRows", resourceCulture);
            }
        }
        
        internal static string Prioritise {
            get {
                return ResourceManager.GetString("Prioritise", resourceCulture);
            }
        }
        
        internal static string MustBeNumber {
            get {
                return ResourceManager.GetString("MustBeNumber", resourceCulture);
            }
        }
        
        internal static string CommandNotRecognised {
            get {
                return ResourceManager.GetString("CommandNotRecognised", resourceCulture);
            }
        }
        
        internal static string CreatedOctopusTask {
            get {
                return ResourceManager.GetString("CreatedOctopusTask", resourceCulture);
            }
        }
        
        internal static string CreatedReleaseForProject {
            get {
                return ResourceManager.GetString("CreatedReleaseForProject", resourceCulture);
            }
        }
        
        internal static string CreatingOctopusTaskForProject {
            get {
                return ResourceManager.GetString("CreatingOctopusTaskForProject", resourceCulture);
            }
        }
        
        internal static string CreatingReleaseForProject {
            get {
                return ResourceManager.GetString("CreatingReleaseForProject", resourceCulture);
            }
        }
        
        internal static string DeploymentComplete {
            get {
                return ResourceManager.GetString("DeploymentComplete", resourceCulture);
            }
        }
        
        internal static string DeploymentElapsedTime {
            get {
                return ResourceManager.GetString("DeploymentElapsedTime", resourceCulture);
            }
        }
        
        internal static string DeploymentFailed {
            get {
                return ResourceManager.GetString("DeploymentFailed", resourceCulture);
            }
        }
        
        internal static string DeploymentSummary {
            get {
                return ResourceManager.GetString("DeploymentSummary", resourceCulture);
            }
        }
        
        internal static string DeploymentSummaryCompleted {
            get {
                return ResourceManager.GetString("DeploymentSummaryCompleted", resourceCulture);
            }
        }
        
        internal static string DeploymentSummaryFailed {
            get {
                return ResourceManager.GetString("DeploymentSummaryFailed", resourceCulture);
            }
        }
        
        internal static string DeploymentSummaryTotal {
            get {
                return ResourceManager.GetString("DeploymentSummaryTotal", resourceCulture);
            }
        }
        
        internal static string FailedProjects {
            get {
                return ResourceManager.GetString("FailedProjects", resourceCulture);
            }
        }
        
        internal static string FailedProjectLink {
            get {
                return ResourceManager.GetString("FailedProjectLink", resourceCulture);
            }
        }
        
        internal static string FetchedReleaseForProject {
            get {
                return ResourceManager.GetString("FetchedReleaseForProject", resourceCulture);
            }
        }
        
        internal static string FetchingReleaseForProject {
            get {
                return ResourceManager.GetString("FetchingReleaseForProject", resourceCulture);
            }
        }
        
        internal static string OctopusTaskNotFound {
            get {
                return ResourceManager.GetString("OctopusTaskNotFound", resourceCulture);
            }
        }
        
        internal static string ProfileFileNotFound {
            get {
                return ResourceManager.GetString("ProfileFileNotFound", resourceCulture);
            }
        }
        
        internal static string ProjectDeployedToEnvironment {
            get {
                return ResourceManager.GetString("ProjectDeployedToEnvironment", resourceCulture);
            }
        }
        
        internal static string ProjectFailedToDeploy {
            get {
                return ResourceManager.GetString("ProjectFailedToDeploy", resourceCulture);
            }
        }
        
        internal static string ProjectFailedWithError {
            get {
                return ResourceManager.GetString("ProjectFailedWithError", resourceCulture);
            }
        }
        
        internal static string RawLog {
            get {
                return ResourceManager.GetString("RawLog", resourceCulture);
            }
        }
        
        internal static string ShipItSharpDeployment {
            get {
                return ResourceManager.GetString("ShipItSharpDeployment", resourceCulture);
            }
        }
        
        internal static string ShipItSharpDeploymentToTarget {
            get {
                return ResourceManager.GetString("ShipItSharpDeploymentToTarget", resourceCulture);
            }
        }
        
        internal static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        internal static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        internal static string StatusRun {
            get {
                return ResourceManager.GetString("StatusRun", resourceCulture);
            }
        }
        
        internal static string TaskQueuedWaiting {
            get {
                return ResourceManager.GetString("TaskQueuedWaiting", resourceCulture);
            }
        }
        
        internal static string TaskStatusProgress {
            get {
                return ResourceManager.GetString("TaskStatusProgress", resourceCulture);
            }
        }
    }
}
